typography_spectrum: 0.6304718025494367
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#1c86eb'
    - '#113f97'
    - '#a1a1a1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20541438274085522
analytics:
  google: null
  facebook: null
  twitter: null
name: Kerry Keating
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 3.21.16 In Studio on Comcast Sports Talk Live
    id: 3af27a35-8ec6-4db5-820f-132396890e0e
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: www.kerrykeating.com
description: Media
purpose: []
