name: Kerry Keating
favicon: null
layout_spectrum: 0.1774193
typography_spectrum: 0.1039427
title: www.kerrykeating.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aba9aa'
    - '#000000'
    - '#3b3b3b'
    - '#ee090b'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
