typography_spectrum: 0.6304718025494367
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#1c86eb'
    - '#113f97'
    - '#a1a1a1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20541438274085522
analytics:
  google: null
  facebook: null
  twitter: null
name: Kerry Keating
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: >-
      6.1.16 In Studio Comcast STL Telestrator breaking down the Cavs for the
      Finals
    id: 3bc9fd3e-41dd-4e4d-a9b3-eafdf5d1ed9a
    type: content
  - name: Sitting in on the Adidas Nations Semi Final International Game
    id: f1e4d37d-a1da-4424-ae96-a92a254a402b
    type: content
  - name: In studio at Comcast STL with Jim Kozimor and Scott Ostler
    id: c1ef9f06-5df4-4387-a8be-c72f4c1ea40e
    type: content
  - name: Western Conference Finals Preview on CSN SportsTalk Live 5.16.16
    id: 4812a27b-c463-46e7-b63b-8677c3d694da
    type: content
  - name: 3.21.16 In Studio on Comcast Sports Talk Live
    id: 3af27a35-8ec6-4db5-820f-132396890e0e
    type: content
  - name: 3.14.16 Comcast STL March Madness Special
    id: ff6155d6-e3d0-4cf1-a311-6e33875947be
    type: content
  - name: 5.26.16 In Studio KNBR with Garry and Larry
    id: aa536599-396b-424f-933c-37baffccbe7c
    type: content
  - name: 5-16-16 KNBR in studio
    id: c55ba615-7906-4cee-8dca-ab0c10bee026
    type: content
  - name: KNBR 4-25-16
    id: 7f753093-3da2-4d89-a640-acbbb1983451
    type: content
  - name: 3-28-16 in KNBR Studio with Larry
    id: f3bcf74c-d1ba-4ec8-9e47-1adac3ab3f5f
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: www.kerrykeating.com
description: click top right for links to TV appearances
purpose: []
