name: Kerry Keating
favicon: null
layout_spectrum: 0.24017
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#fefefe'
    - '#c4c4c6'
    - '#606062'
    - '#61371e'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
