name: Kerry Keating
favicon: null
layout_spectrum: 0.2007169
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Official Website for Kerry Keating
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030205'
    - '#FAFAFC'
    - '#909092'
    - '#B3B3B5'
    - '#535254'
  brandStrength: 0.625
  lightness: 0.5017921
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
