name: Kerry Keating
favicon: null
layout_spectrum: 0.3137
typography_spectrum: 1
title: Official Website for Kerry Keating
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#fefefe'
    - '#c4c4c6'
    - '#606062'
    - '#61371e'
  brandStrength: 0.375
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
