title: www.kerrykeating.com
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8763441
  brandStrength: 0.2616487
  lightness: 0.5071685
  brandColors:
    - '#000000'
    - '#9A8D84'
    - '#023D37'
    - '#FF3A0E'
    - '#6D0E02'
  rhythmicContrast: 0.2706093
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Kerry Keating
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1039427
layout_spectrum: 0.1774193
